name: CustomChunkLoader
main: org.kayteam.chunkloader.ChunkLoader
version: ${project.version}
author: OGTime
website: https://github.com/ogtime
api-version: 1.13
softdepend: [ Multiverse-Core, WorldEdit ]
commands:
  removechunkregion:
    description: RemoveChunkRegion
    permission: chunkloader.removechunkregion
  addchunkregion:
    description: AddChunkRegion
    permission: chunkloader.addchunkregion
  removechunkregion:
    description: RemoveChunkRegion
    permission: chunkloader.removechunkregion
  addchunk:
    description: AddChunk
    permission: chunkloader.addchunk
  removechunk:
    description: RemoveChunk
    permission: chunkloader.removechunk
  chunkloader:
    description: ChunkLoader
    aliases:
      - cl
      - cloader
      - chunkl
permissions:
  chunkloader.admin:
    children:
      - chunkloader.addchunk
      - chunkloader.removechunk
      - chunkloader.addchunkregion
      - chunkloader.removechunkregion
      - chunkloader.list
      - chunkloader.tp
      - chunkloader.menu
      - chunkloader.on
      - chunkloader.off
      - chunkloader.reload
      - chunkloader.give
